# NumPy and Pandas for Anomaly Detection

Master NumPy arrays, Pandas DataFrames, and vectorized operations for efficient data processing.

## 1. NumPy Array Creation

In [1]:
import numpy as np

# Create arrays
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)
print("Shape:", arr1.shape)
print("Data type:", arr1.dtype)

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr2d)
print("Shape:", arr2d.shape)

1D Array: [1 2 3 4 5]
Shape: (5,)
Data type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


## 2. NumPy Array Generation

In [2]:
# Generate arrays efficiently
zeros = np.zeros((3, 3))
print("Zeros:\n", zeros)

ones = np.ones((2, 4))
print("\nOnes:\n", ones)

range_arr = np.arange(0, 10, 2)
print("\nRange:", range_arr)

linspace_arr = np.linspace(0, 1, 5)
print("\nLinspace:", linspace_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Range: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]


## 3. NumPy Random Data (for Simulating Network Traffic)

In [3]:
# Generate synthetic flow duration data
np.random.seed(42)
normal_flows = np.random.exponential(500, 1000)  # Normal traffic
anomalous_flows = np.random.exponential(50, 80)  # Attack traffic

print(f"Normal flows (first 10): {normal_flows[:10]}")
print(f"Anomalous flows (first 10): {anomalous_flows[:10]}")
print(f"\nNormal flows stats: Mean={normal_flows.mean():.1f}, Std={normal_flows.std():.1f}")
print(f"Anomalous flows stats: Mean={anomalous_flows.mean():.1f}, Std={anomalous_flows.std():.1f}")

Normal flows (first 10): [ 234.63404499 1505.06071546  658.37284677  456.47127689   84.81243523
   84.79814596   29.9193843  1005.61543224  459.54107681  615.62503085]
Anomalous flows (first 10): [ 10.2365141   39.03349231 103.15708971  65.88038896  82.1396913
  53.76188576  58.92769181  94.5885994   14.36197578  33.61088331]

Normal flows stats: Mean=486.3, Std=486.0
Anomalous flows stats: Mean=60.3, Std=60.0


## 4. NumPy Vectorization (Element-wise Operations)

In [4]:
# Compute Z-scores without loops (vectorization)
data = np.array([100, 150, 200, 220, 180, 110, 500])  # Note: 500 is anomaly

mean = data.mean()
std = data.std()

# Vectorized Z-score computation
z_scores = (data - mean) / std

print("Data:", data)
print("Mean:", mean)
print("Std:", std)
print("Z-scores:", z_scores)
print("\nAnomalies (|Z| > 3):", data[np.abs(z_scores) > 3])

Data: [100 150 200 220 180 110 500]
Mean: 208.57142857142858
Std: 125.8603048086672
Z-scores: [-0.8626344  -0.46536856 -0.06810272  0.09080362 -0.22700905 -0.78318123
  2.31549234]

Anomalies (|Z| > 3): []


## 5. Pandas DataFrame Creation

In [5]:
import pandas as pd

# Create DataFrame from data
data = {
    'Flow Duration': [500, 450, 480, 520, 100, 2000],
    'Total Packets': [10, 12, 8, 11, 1000, 50],
    'Bytes Sent': [2000, 2100, 1900, 2050, 50000, 3000]
}

df = pd.DataFrame(data)
print("DataFrame:")
print(df)
print("\nShape:", df.shape)
print("Columns:", df.columns.tolist())
print("Data types:\n", df.dtypes)

DataFrame:
   Flow Duration  Total Packets  Bytes Sent
0            500             10        2000
1            450             12        2100
2            480              8        1900
3            520             11        2050
4            100           1000       50000
5           2000             50        3000

Shape: (6, 3)
Columns: ['Flow Duration', 'Total Packets', 'Bytes Sent']
Data types:
 Flow Duration    int64
Total Packets    int64
Bytes Sent       int64
dtype: object


## 6. Pandas Column Access and Operations

In [ ]:
# Access columns
duration = df['Flow Duration']
print("Flow Duration column:")
print(duration.values)

# Create new column
df['Bytes Per Packet'] = df['Bytes Sent'] / df['Total Packets']
print("\nWith new column:")
print(df[['Flow Duration', 'Bytes Per Packet']])

# Vectorized operations
df['Bytes Doubled'] = df['Bytes Sent'] * 2
print("\nAfter doubling bytes:")
print(df[['Bytes Sent', 'Bytes Doubled']])

## 7. Pandas Filtering and Selection

In [ ]:
# Filter for anomalies
anomalies = df[df['Flow Duration'] > 1000]
print("Anomalous flows (duration > 1000):")
print(anomalies)

# Multiple conditions
suspicious = df[(df['Flow Duration'] < 200) | (df['Total Packets'] > 500)]
print("\nSuspicious flows (duration < 200 OR packets > 500):")
print(suspicious)

# Count anomalies
anomaly_count = len(anomalies)
print(f"\nTotal anomalies: {anomaly_count} out of {len(df)}")

## 8. Pandas Summary Statistics

In [ ]:
# Summary statistics
print("Describe:")
print(df.describe())

# Per-column operations
print("\nMean:")
print(df.mean())

print("\nMedian:")
print(df.median())

print("\nStandard Deviation:")
print(df.std())

## 9. NumPy and Pandas Integration

In [ ]:
# Convert DataFrame to NumPy array
numeric_cols = df[['Flow Duration', 'Total Packets', 'Bytes Sent']]
data_array = numeric_cols.values

print("NumPy array from DataFrame:")
print(data_array)
print("Shape:", data_array.shape)

# Vectorized normalization
data_normalized = (data_array - data_array.mean(axis=0)) / data_array.std(axis=0)
print("\nNormalized data:")
print(data_normalized)

# Back to DataFrame
df_normalized = pd.DataFrame(data_normalized, columns=numeric_cols.columns)
print("\nAs DataFrame:")
print(df_normalized)

## Summary

- **NumPy**: Fast, vectorized numerical operations on arrays
- **Pandas**: Table-like DataFrames for data manipulation
- **Vectorization**: 100x faster than loops for large datasets
- **Integration**: Easy conversion between NumPy and Pandas

Perfect for processing thousands of network flows!